/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/dashboard/map/': RouteRecordInfo<'/dashboard/map/', '/dashboard/map', Record<never, never>, Record<never, never>>,
    '/dashboard/workTable/': RouteRecordInfo<'/dashboard/workTable/', '/dashboard/workTable', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/monitor/info/': RouteRecordInfo<'/monitor/info/', '/monitor/info', Record<never, never>, Record<never, never>>,
    '/monitor/loginLog/': RouteRecordInfo<'/monitor/loginLog/', '/monitor/loginLog', Record<never, never>, Record<never, never>>,
    '/monitor/operationLog/': RouteRecordInfo<'/monitor/operationLog/', '/monitor/operationLog', Record<never, never>, Record<never, never>>,
    '/project/analysisTask/': RouteRecordInfo<'/project/analysisTask/', '/project/analysisTask', Record<never, never>, Record<never, never>>,
    '/project/analysisTask/[id]': RouteRecordInfo<'/project/analysisTask/[id]', '/project/analysisTask/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/contract/': RouteRecordInfo<'/project/contract/', '/project/contract', Record<never, never>, Record<never, never>>,
    '/project/contract/[id]': RouteRecordInfo<'/project/contract/[id]', '/project/contract/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/device/': RouteRecordInfo<'/project/device/', '/project/device', Record<never, never>, Record<never, never>>,
    '/project/device/[id]': RouteRecordInfo<'/project/device/[id]', '/project/device/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/factory/': RouteRecordInfo<'/project/factory/', '/project/factory', Record<never, never>, Record<never, never>>,
    '/project/factory/[id]': RouteRecordInfo<'/project/factory/[id]', '/project/factory/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/': RouteRecordInfo<'/project/valve/', '/project/valve', Record<never, never>, Record<never, never>>,
    '/project/valve/[id]': RouteRecordInfo<'/project/valve/[id]', '/project/valve/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/detail/[id]': RouteRecordInfo<'/project/valve/detail/[id]', '/project/valve/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/history/[id]': RouteRecordInfo<'/project/valve/history/[id]', '/project/valve/history/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/historyData/[id]': RouteRecordInfo<'/project/valve/historyData/[id]', '/project/valve/historyData/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/runInfo/[id]': RouteRecordInfo<'/project/valve/runInfo/[id]', '/project/valve/runInfo/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/score/[id]': RouteRecordInfo<'/project/valve/score/[id]', '/project/valve/score/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/project/valve/workOrder/[id]': RouteRecordInfo<'/project/valve/workOrder/[id]', '/project/valve/workOrder/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/dept/': RouteRecordInfo<'/system/dept/', '/system/dept', Record<never, never>, Record<never, never>>,
    '/system/dictData/': RouteRecordInfo<'/system/dictData/', '/system/dictData', Record<never, never>, Record<never, never>>,
    '/system/dictData/[id]': RouteRecordInfo<'/system/dictData/[id]', '/system/dictData/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/system/dictDataTree/': RouteRecordInfo<'/system/dictDataTree/', '/system/dictDataTree', Record<never, never>, Record<never, never>>,
    '/system/dictType/': RouteRecordInfo<'/system/dictType/', '/system/dictType', Record<never, never>, Record<never, never>>,
    '/system/menu/': RouteRecordInfo<'/system/menu/', '/system/menu', Record<never, never>, Record<never, never>>,
    '/system/post/': RouteRecordInfo<'/system/post/', '/system/post', Record<never, never>, Record<never, never>>,
    '/system/role/': RouteRecordInfo<'/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/rule/': RouteRecordInfo<'/system/rule/', '/system/rule', Record<never, never>, Record<never, never>>,
    '/system/unit/': RouteRecordInfo<'/system/unit/', '/system/unit', Record<never, never>, Record<never, never>>,
    '/system/user/': RouteRecordInfo<'/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
  }
}
